# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07geo_int\"\x07\n\x05\x45mpty\"{\n\x07Request\x12\r\n\x05input\x18\x01 \x01(\t\x12\x30\n\x08metadata\x18\x02 \x03(\x0b\x32\x1e.geo_int.Request.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9e\x01\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x31\n\x08metadata\x18\x04 \x03(\x0b\x32\x1f.geo_int.Response.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2}\n\x0cModelService\x12\x35\n\x0eProcessRequest\x12\x10.geo_int.Request\x1a\x11.geo_int.Response\x12\x36\n\x0bHealthCheck\x12\x0e.geo_int.Empty\x1a\x17.geo_int.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST_METADATAENTRY']._loaded_options = None
  _globals['_REQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_RESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_RESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_REQUEST']._serialized_start=35
  _globals['_REQUEST']._serialized_end=158
  _globals['_REQUEST_METADATAENTRY']._serialized_start=111
  _globals['_REQUEST_METADATAENTRY']._serialized_end=158
  _globals['_RESPONSE']._serialized_start=161
  _globals['_RESPONSE']._serialized_end=319
  _globals['_RESPONSE_METADATAENTRY']._serialized_start=111
  _globals['_RESPONSE_METADATAENTRY']._serialized_end=158
  _globals['_HEALTHRESPONSE']._serialized_start=321
  _globals['_HEALTHRESPONSE']._serialized_end=353
  _globals['_MODELSERVICE']._serialized_start=355
  _globals['_MODELSERVICE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
