import geopandas as gpd
import numpy as np
import rasterio
from rasterio.mask import mask

# globals
output_path = "D:/Projects/Ships/S2"


# Helper to read a single-band raster and mask it
def read_and_mask(band_path, geoms_json, shape_box):
    with rasterio.open(band_path) as src:
        # If shapefile CRS differs from raster CRS, reproject geometries
        if (
            shape_box.crs is not None
            and src.crs is not None
            and shape_box.crs != src.crs
        ):
            geoms_proj = shape_box.to_crs(src.crs).geometry.values
            geoms_json_local = [g.__geo_interface__ for g in geoms_proj]
        else:
            geoms_json_local = geoms_json

        data, transform = mask(src, geoms_json_local, crop=True, all_touched=True)
        profile = src.profile.copy()
        profile.update(
            {
                "height": data.shape[1],
                "width": data.shape[2],
                "transform": transform,
                "count": 1,
            }
        )
        return data[0], profile  # single-band array and profile


def roi_cut_stack(in_blue, in_green, in_red, rio_box, roi_3b_image):
    shape_box = gpd.read_file(rio_box)
    geoms = shape_box.geometry.values
    geoms_json = [g.__geo_interface__ for g in geoms]

    # Read & mask each band
    b_band, profile = read_and_mask(in_blue, geoms_json, shape_box)
    g_band, _ = read_and_mask(in_green, geoms_json, shape_box)
    r_band, _ = read_and_mask(in_red, geoms_json, shape_box)

    # Stack bands into (count, height, width)
    rgb = np.stack([b_band, g_band, r_band], axis=0)

    # Update profile for 3-band output
    profile.update({"count": 3, "dtype": rgb.dtype})

    # Write output (GeoTIFF)
    out_tmp_3b_roi = output_path + "/" + roi_3b_image
    with rasterio.open(out_tmp_3b_roi, "w", **profile) as dst:
        dst.write(rgb)

    print("Saved:", out_tmp_3b_roi)
    return out_tmp_3b_roi


def image_tiler(out_tmp_3b_roi, docks_shp, chips_path):
    # Next code to be written
    pass


######################
# Code completed
######################
# Cut 3 bands to Region of Interest Envelope
# Stack 3 bands
######################
# Code to be written
######################
# cycle through Dock ID
# Select dock by "ID" and clip stacked 3 band image
# form output image filename
# output image chip for use within model
######################

if __name__ == "__main__":
    # set target date; generated by system time
    date_stamp = "20260413"

    # set input data file path; will be S3 bucket in future
    input_path = "D:/Projects/Ships/S2/S2C_MSIL2A_20260413T070731_N0512_R106_T39RVK_20260413T105313.SAFE/GRANULE/L2A_T39RVK_A008370_20260413T071338/IMG_DATA/R10m"

    # set output data file path; to be determined
    chips_path = output_path + "/" + date_stamp + "/chips"

    # set output temp 3b region of interest image; to be determined
    roi_3b_image = "tmp_roi_3b_image.tif"

    # set region of interest shapefile to use; This is fixed for project
    roi_box = "D:/Projects/Ships/ROI_box.shp"

    # set shapefile of target docks; This is fixed for project
    docks_shp = "D:/Projects/Ships/RasTanura_Docks.shp"

    # set input individual band images to use; Names will be adjusted based on S3 data store
    in_blue = input_path + "/T39RVK_20260413T070731_B03_10m.jp2"
    in_green = input_path + "/T39RVK_20260413T070731_B04_10m.jp2"
    in_red = input_path + "/T39RVK_20260413T070731_B08_10m.jp2"

    # begin data processing steps:
    # collect bands and cut to ROI
    out_tmp_3b_roi = roi_cut_stack(in_blue, in_green, in_red, roi_box, roi_3b_image)

    # cut tmp 3b image into dock-specific image chips for model analysis
    image_tiler(out_tmp_3b_roi, docks_shp, chips_path)
